global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'monitoring_server'
    static_configs:
      -  targets: ['10.0.1.90:9100']

  - job_name: 'nginx_server'
    static_configs:
      - targets: ['10.0.1.99:9100']

  - job_name: 'prometheus_container'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana_container'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki_container'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['10.0.1.99:9113']