num_of_machines = 3 #Number of virtual machines
first_ip = 11  #IP address of the first virtual machine

(1..num_of_machines).each do |num|

  folder_machine = "./sync_folder/Virtual-machine#{num}"
  FileUtils::mkdir_p folder_machine #Create folder for each machine

  Vagrant.configure("2") do |config|
    config.vm.define "vm#{num}" do |vm|
      vm.vm.box = "bento/ubuntu-24.04"
      vm.vm.network "private_network", ip: "192.168.100.#{first_ip+num-1}" 
      vm.vm.synced_folder folder_machine, "/vagrant_sync_folder"
      vm.vm.host_name = "Virtual-machine#{num}"
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      vm.vm.provision "shell", inline: "echo hello from VM#{num}"
    end
  end
end