---
- name: Ensure SSH keys are configured
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', 'files/instance_test_key.pub') }}"

- name: Apt cache (apt update)
  apt:
    update_cache: yes

- name: Install packages vim, git, mc, ufw, htop
  apt:
    name:
      - vim
      - git
      - ufw
      - htop
    state: present