apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: pod
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: ebs-claim
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: ebs-claim
    persistentVolumeClaim:
      claimName: ebs-storage