apiVersion: v1
kind: Namespace
metadata:
  name: hw-20

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: hw-20
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "4"