apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
  namespace: hw-20
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/redis0"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
  namespace: hw-20
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/redis1"