Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.define "public" do |vm1|
    vm1.vm.box = "bento/ubuntu-24.04"
    vm1.vm.network "public_network"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.synced_folder "./sync_folder", "/vagrant_sync_folder"
    vm1.vm.host_name = "Public-server"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 3
    end
    vm1.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get upgrade -y
    apt-get install -y nginx
    sudo cp /vagrant_sync_folder/index.html /var/www/html 
      #or ln -fs /vagrant_sync_folder/index.html /var/www/html - Детальнiше в README.md!
    sudo systemctl restart nginx
    SHELL
  end
  
  config.vm.define "private" do |vm2|
    vm2.vm.box = "bento/ubuntu-24.04"
    vm2.vm.network "private_network", ip: "192.168.100.33"
    vm2.vm.synced_folder "./sync_folder", "/vagrant_sync_folder"
    vm2.vm.host_name = "private-server"
    vm2.vm.provision "shell", inline: "bash /vagrant_sync_folder/script.sh"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end


  config.vm.define "server" do |vm3|
    vm3.vm.box = "bento/ubuntu-24.04"
    vm3.vm.network "public_network", ip: "192.168.100.33", bridge: "MediaTek Wi-Fi 6/6E Wireless USB LAN Card"
    vm3.vm.synced_folder "./server_folder", "/server_folder"
    vm3.vm.host_name = "server"
    vm3.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end

