---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Deploy index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Deploy default Nginx configuration file
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root

- name: Restart Nginx
  service:
    name: nginx
    state: restarted