AWSTemplateFormatVersion: '2010-09-09'
Description: ''

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  
  Public:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Public
      RouteTableId: !Ref PublicRouteTable

  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      RoleName: EC2S3ReadOnlyRole
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyInstanceRole

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0852de09092f3a061 
      SubnetId: !Ref Public
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: instance_test_key
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: backet-2394i23j12
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: CloudFormation
          Value: !Ref AWS::StackName

Outputs:
  InstancePublicIP:
    Value: !GetAtt MyEC2Instance.PublicIp
    Description: Public IP of the EC2 instance.

  BucketName:
    Value: !Ref MyS3Bucket
    Description: Name of the S3 Bucket.