apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
  namespace: homework
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/nginx"