apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  namespace: homework
spec:
  resources: 
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
