- name: Set logging
  ufw:
    logging: on

- name: Allow ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80     #Http
    - 443    #Https

- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Show UFW status
  command: ufw status verbose
  register: ufw_status

- debug:
    var: ufw_status.stdout_lines

